source "https://rubygems.org"

gem "rails", "4.2.4"
gem "materialize-sass"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "paypal-express"
gem "omniauth-google-oauth2"
gem "omniauth-facebook"
gem "pry"
gem "puma"
gem "will_paginate-materialize", "0.1.2"
gem "figaro"
gem "metric_fu"
gem "sidekiq"
gem "mocha"
gem "cocoon"
gem "responders", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc

group :development, :test do
  gem "sqlite3"
  gem "byebug"
  gem "simplecov"
  gem "simplecov-shield"
  gem "rspec-rails", "~> 3.0"
  gem "capybara"
  gem "selenium-webdriver"
  gem "database_cleaner"
  gem "rack_session_access"
  gem "codeclimate-test-reporter", require: nil
end

group :development do
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "letter_opener"
  gem "launchy"
end

group :production do
  ruby "2.2.3"
  gem "pg", "0.17.1"
  gem "rails_12factor", "0.0.2"
end